



stages:



# Build Stage

- stage: BuildAndTest

  jobs:

  - job: BuildAndTest

    pool: ashutosh
      
    steps:



    # Create or update the ACR resource

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'AzureSC'
        subscriptionId: '9e58d72f-351b-4828-a709-7758de05531b'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'cswebappdocker789-rg'
        location: 'East US'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.kubernetes/aks/azuredeploy.json'
        deploymentMode: 'Incremental'